### ISSUE TITLE
CAN NOT LOGIN THE WEB

### ISSUE THREAD

**Issue by adersonleo** [mkschreder/juci#61]
I think i do everything right with compile,  and I can see the login page, I also use orangectl adduser and orangectl passwd user password the set the password, but I still can not login the WEB, I compile after your step.
I really like this project,
thank you!

**Comment by adersonleo** [comment]
It's always show "Please enter correct username and password!"

**Comment by mkschreder** [comment]
maybe you don't have sha1sum cli utility? Check uml build script in the
juci-feed-openwrt repo for required steps to select packages for a basic
build.

**Comment by adersonleo** [comment]
@mkschreder 
Thank you for your reply!
I do all the step again, and lucky, I am already login, But I still have one problem , I can login with Mircosoft Eage Brower,When I try to login with Chrome. It's still show  Please enter correct username and password!, I login with the same password in Eage
Thank you!

**Comment by Pillar1989** [comment]
Hi mkschreder
I have installed all the software package which you pointed, but i still cannt login the web. Must I add admin user ? I cannt use default root account.

**Comment by Pillar1989** [comment]
Thanks other issue, I'm login, I need do two commands.
orangectl adduser admin
orangectl passwd admin admin

Where can we find detail deploy documents ?

**Comment by mkschreder** [comment]
Check the user mode linux build script. It explains all the steps you need
to take when starting with a fresh openwrt repo to get all the packages
installed correctly.

On 24 Sep 2016 12:16, "Baozhu Zuo" <notifications@github.com> wrote:

Hi mkschreder
I have installed all the software package which you pointed, but i still
cannt login the web. Must I add admin user ? I cannt use default root
account.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mkschreder/juci/issues/61#issuecomment-249357330>, or mute
the thread
